source ~/.tmux/custom/keybindings.conf


# Enable mouse support
set -g mouse on


# Increase history limit
set-option -g history-limit 10000


# Numbering windows / panes
set  -g base-index 1
setw -g pane-base-index 1
set  -g renumber-windows on


# Enable Powerline
run-shell 'powerline-config tmux setup'


# ALWAYS SET THIS LINE LAST
source ~/.tmux/custom/plugins.conf
