source ~/.tmux/custom/keybindings.conf

# Enable mouse support
set -g mouse on


# Increase history limit
set-option -g history-limit 10000

# Numbering windows / panes
set  -g base-index 1
setw -g pane-base-index 1
set  -g renumber-windows on

# {{{Status Bar
set -g status-bg "#262626"
set -g status-fg white

set -g status-position top
set -g status-justify left
set -g status-style 'bg=colour18 fg=white'
set -g status-left ''
set -g status-right '#[fg=#3D484D]#[fg=white,bg=#3D484D] %d/%m #[fg=#83C092,bg=#3D484D]#[fg=#2D353B,bg=#83C092] %H:%M:%S #[fg=#83C092,bg=default]'
set -g status-right-length 50
set -g status-left-length 20

setw -g window-status-current-style 'fg=#3D484D bg=#A7C080 bold'
setw -g window-status-current-format '#[fg=#A7C080,bg=#262626]#[fg=#343F44,bg=#A7C080]#I#[fg=#475258]:#[fg=#3D484D]#W#[fg=#56635f]#F#[fg=#A7C080,bg=#262626]'

setw -g window-status-style 'fg=white bg=#475258'
setw -g window-status-format ' #I#[fg=white]:#[fg=white]#

# }}}
# ALWAYS SET THIS LINE LAST
source ~/.tmux/custom/plugins.conf
