# Reload tmux.conf
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# User C-Space as leader key
unbind C-Space
set -g prefix C-SPace
bind C-Space send-prefix

# Intuitive split commands
bind v split-window -hc "#{pane_current_path}"
bind h split-window -vc "#{pane_current_path}"
bind V split-window -hc "#{pane_current_path}"
bind H split-window -vc "#{pane_current_path}"

# Intuitive swap-window keybindings
bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1

# New window keeps current path
bind c new-window -c "#{pane_current_path}"

# Resizing windows
bind -r C-j resize-pane -D 15
bind -r C-k resize-pane -U 15
bind -r C-h resize-pane -L 15
bind -r C-l resize-pane -R 15
