# Reload tmux.conf
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# User C-Space as leader key
unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

# select panels
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Intuitive split commands
bind v split-window -hc "#{pane_current_path}"
bind V split-window -hc "#{pane_current_path}"

# Intuitive swap-window keybindings
bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1

# New window keeps current path
bind c new-window -c "#{pane_current_path}"

# Resizing windows
bind -r C-j resize-pane -D 15
bind -r C-k resize-pane -U 15
bind -r C-h resize-pane -L 15
bind -r C-l resize-pane -R 15
