#!/bin/sh

dependencies="
\tzsh\n
\tcurl\n
\twget\n
\tunzip\n
\tgit\n
\tpip (for python 3)\n
"

nodejs_lts_latest='18.12.1'

exit_program() {
    case "$1" in
        2)
            echo "$2 is required for bootstrap to work. Here are the dependencies required for bootstrap:"
            echo $dependencies
            ;;
        *)
            echo "invalid exit code: $1"
    esac
    
    echo 'If you are able to, please run ~/.config/yadm/bootstrap once you have finished fixing your errors'
    exit 1
}

# from https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
command_exists() {
  command -v "$1" >/dev/null 2>&1
}

# make sure that all dependencies are installed
[ -f /usr/bin/git ] || exit_program 2 git
[ -f /usr/bin/zsh ] || exit_program 2 zsh
command_exists pip || exit_program 2 pip
[ -f /usr/bin/curl ] || exit_program 2 curl

# starship prompt for bash & other shells 😊
curl -sS https://starship.rs/install.sh | sh

# install fnm and the latest lts release
curl -fsSL https://fnm.vercel.app/install | bash
fnm install nodejs_lts_latest 

# install pyenv and pipenv
curl https://pyenv.run | sh
pip install pipenv

# install oh-my-zsh and the plugins dependencies
wget -P $HOME/omz-temp/ https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
$HOME/omz-tmp/install.sh --keep-zshrc
rm -rf $HOME/omz-tmp/

git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
pip install thefuck
