#!/bin/sh

dependencies=("git" "pip" "pipenv" "zsh" "curl" "wget" "unzip")
nodejs_version="nodejs@18.15.0"
bob_nvim_version="latest"

print_error()
{
    local RED="\033[31m"
    local RED_BOLD="\033[1;31m"
    local RESET="\033[0m"

    printf "%b[ERROR]%b " "$RED_BOLD" "$RED"
    printf "%s%b\n" "$1" "$RESET"
}

print_warn()
{
    local YELLOW="\033[33m"
    local YELLOW_BOLD="\033[1;33m"
    local RESET="\033[0m"

    printf "%b[WARN]%b " "$YELLOW_BOLD" "$YELLOW"
    printf "%s%b\n" "$1" "$RESET"
}

print_okay()
{
    local GREEN="\033[32m"
    local GREEN_BOLD="\033[1;32m"
    local RESET="\033[0m"

    printf "%b[OKAY]%b " "$GREEN_BOLD" "$GREEN"
    printf "%s%b\n" "$1" "$RESET"
}

exit_program() {
    case "$1" in
        1)
            print_error "$2 is required for bootstrap to work. Here are the dependencies required for bootstrap:"
            for dependency in "$(dependencies[@])";
            do
                echo -e "\t${dependency}\n"
            done
            ;;
        *)
            print_error "invalid exit code: $1"
    esac
    
    echo 'If you are able to, please run ~/.config/yadm/bootstrap once you have finished fixing your errors'
    exit 1
}

command_exists() 
{
    for cmd_name in "$@"; do
        command -v "$cmd_name" >/dev/null
        cmd_status=$?

        if [ "$cmd_status" -eq 0 ];
        then
            print_okay "$cmd_name is an executable"
        else
            print_error "$cmd_name isn't an executable"
        fi

        overall_status=$(( overall_status > cmd_status ? overall_status : cmd_status ))
    done

    return $overall_status
}

# make sure that all dependencies are installed
if ! command_exists git zsh pip curl wget unzip pipenv;
then
    exit_program 2
fi

print_warn "Stashing current configs..."
# stash current config in yadm
$(which yadm) stash
print_okay "Current configs stashed!"

# Install FiraCode Nerd Font
print_warn "Installing the FiraCode Nerd Font..."
git clone --filter=blob:none --sparse https://github.com/ryanoasis/nerd-fonts
cd nerd-fonts
git sparse-checkout add patched-fonts/FiraCode
./install.sh FiraCode
cd - # switch back to prev directory
print_okay "Font installed!"

# starship prompt for bash & other shells 😊
print_warn "Installing starship prompt..."
curl -sS https://starship.rs/install.sh | sh -s -- -y
print_okay "starship installed!"

# rustup installation
print_warn "Installing rustup..."
curl https://sh.rustup.rs -sSf | sh -s -- -y
print_okay "starship installed!"

# cargo install packages
print_warn "Installing cargo-binstall. This will take a moment..."
$HOME/.cargo/bin/cargo install --quiet cargo-binstall
print_okay "cargo-binstall installed!"

print_warn "Installing rtx-cli..."
$HOME/.cargo/bin/cargo-binstall -y rtx-cli 
print_okay "rtx-cli installed!"

print_warn "Installing bob-nvim..."
$HOME/.cargo/bin/cargo-binstall -y bob-nvim
print_okay "bob-nvim installed!"

# use specified nodejs version
print_warn "Installing $nodejs_version via rtx-cli..."
$HOME/.cargo/bin/rtx install $nodejs_version
$HOME/.cargo/bin/rtx global $nodejs_version
print_okay "$nodejs_version installed!"

# use the latest stable neovim version
print_warn "Installing NeoVim ${bob_nvim_version} via bob-nvim..."
$HOME/.cargo/bin/bob use $bob_nvim_version
print_okay "NeoVim $bob_nvim_version installed!"

# install oh-my-zsh
print_warn "Installing oh-my-zsh"
wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
sh install.sh --keep-zshrc --unattended
rm install.sh
print_okay "oh-my-zsh installed!"

print_warn "Installing zsh-autosuggestions and zsh-syntax-highlighting..."
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
print_okay "Installed!"

# install tmux plugin manager
print_warn "Installing tmux plugin manager..."
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
print_okay "Installed!"
