# ------------------- #
# Syntax Highlighting #
# ------------------- #
attribute = 'cherry'
type = {fg = 'yellow', modifiers = ['italic']}
constructor = 'green'
constant = 'pink'
string = 'lime'
'string.regexp' = 'yellow'
'string.special' = 'aqua'
'string.special.path' = 'blue'
'string.special.url' = 'blue'
comment = {fg = 'overlay2', modifiers = ['italic']}
variable = 'text'
'variable.builtin' = 'pink'
'variable.other.member' = 'skye'
label = {fg = 'red', modifiers = ['italic']}
punctuation = 'overlay1'
'punctuation.special' = 'aqua'
keyword = {fg = 'red', modifiers = ['italic']}
'keyword.operator' = 'orange'
'keyword.directive' = 'cherry'
operator = 'subtext0'
function = 'green'
'function.builtin' = 'pink'
'function.macro' = 'aqua'
tag = 'skye'
namespace = 'snow'
special = 'lime'
markup = 'text'
'markup.heading' = 'red'
'markup.heading.1' = 'red'
'markup.heading.2' = 'orange'
'markup.heading.3' = 'yellow'
'markup.heading.4' = 'green'
'markup.heading.5' = 'aqua'
'markup.heading.6' = 'blue'
'markup.list' = 'overlay1'
'markup.list.checked' = 'green'
'markup.list.unchecked' = 'overlay1'
'markup.bold' = {fg = 'aqua', modifiers = ['bold']}
'markup.italic' = {fg = 'aqua', modifiers = ['italic']}
'markup.link' = 'blue'
'markup.link.label' = {fg = 'blue', modifiers = ['italic']}
'markup.quote' = {fg = 'overlay2', modifiers = ['italic']}
'markup.raw' = 'overlay1'
'diff.plus' = 'green'
'diff.minus' = 'red'
'diff.delta' = 'aqua'

# -------------- #
# User Interface #
# -------------- #
'ui.background' = {fg = 'text', bg = 'base'}
'ui.background.separator' = {bg = 'surface0'}
'ui.cursor' = {fg = 'base', bg = 'accent', modifiers = ['slow_blink']}
'ui.linenr' = 'surface2'
'ui.statusline' = {fg = 'overlay2', bg = 'mantle'}
'ui.statusline.normal' = {fg = 'base', bg = 'aqua', modifiers = ['bold']}
'ui.statusline.insert' = {fg = 'base', bg = 'text', modifiers = ['bold']}
'ui.statusline.select' = {fg = 'base', bg = 'pink', modifiers = ['bold']}
'ui.bufferline' = {fg = 'subtext0', bg = 'mantle'}
'ui.bufferline.active' = {fg = 'text', bg = 'base', underline = {color = 'text', style = 'line'}}
'ui.bufferline.background' = {bg = 'crust'}
'ui.help' = {fg = 'overlay2', bg = 'surface0' }
'ui.popup' = {fg = 'text', bg = 'mantle'}
'ui.popup.header' = {fg = 'subtext0'}
'ui.window' = 'surface0'
'ui.text' = 'text'
'ui.text.focus' = { fg = 'text', bg = 'surface0', modifiers = ['bold'] }
'ui.text.inactive' = 'overlay1' 
'ui.text.dirctory' = 'blue' 
'ui.virtual' = 'overlay0'
'ui.virtual.ruler' = { bg = 'surface0' }
'ui.virtual.indent-guide' = 'surface0'
'ui.virtual.inlay-hint' = { fg = 'surface1', bg = 'mantle' }
'ui.virtual.jump-label' = { fg = 'accent', modifiers = ['bold'] }
'ui.menu' = {fg = 'text', bg = 'mantle'}
'ui.menu.scroll' = 'accent'
'ui.selection' = {fg = 'base', bg = 'surface1'}
'ui.highlight' =  { bg = 'surface1', modifiers = ['bold'] }
'ui.cursorline' = { bg = 'surface0'}
'ui.cursorcolumn' = { bg = 'surface0'}
warning = 'yellow'
error = 'red'
info = 'aqua'
hint = 'skye'
'diagnostic.hint' = 'skye'
'diagnostic.info' = 'aqua'
'diagnostic.warning' = 'yellow'
'diagnostic.error' = 'red'
'diagnostic.unnecessary' = {fg = 'overlay0', modifiers = ['italic']}
'diagnostic.deprecated' = {fg = 'overlay0', modifiers = ['crossed_out']}

[palette]
red = '#f57f82'
orange = '#f7a182'
yellow = '#f5d098'
lime = '#dbe6af'
green = '#cae0a7'
aqua = '#addeb9'
skye = '#ace0d4'
snow = '#afdfe6'
blue = '#b2cfed'
purple = '#d0bbf0'
pink = '#f3c0e5'
cherry = '#f6cee5'
text = '#f8f9e8'
subtext1 = '#adc9bc'
subtext0 = '#96b4aa'
overlay2 = '#839e9a'
overlay1 = '#6f8788'
overlay0 = '#58686d'
surface2 = '#4a585c'
surface1 = '#3d494d'
surface0 = '#2d393d'
base = '#1d2428'
mantle = '#191e21'
crust = '#171c1f'

accent = '#addeb9'
