format = """
┌\
[](#21282C)\
$username$hostname\
[](bg:#404D44 fg:#21282C)\
$directory\
[](fg:#404D44 bg:#81986D)\
$git_branch\
$git_status\
[](fg:#81986D bg:#E67E80)\
$status\
[ ](fg:#E67E80)
└─▶\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user  = "bg:#21282C bold white"
style_root  = "bg:#21282C bold white"
format      = '[$user]($style)'

[hostname]
style    = 'bg:#21282C'
ssh_only = false
format   = '[$ssh_symbol@$hostname](bold white bg:#21282C)'
trim_at  = '.companyname.com'
disabled = false


[directory]
style             = "bg:#404D44 bold white"
format            = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = " "
"Music"     = " "
"Pictures"  = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
style = 'bg:#81986D bold white'
format = '[ on $symbol$branch(:$remote_branch)]($style)'

[git_status]
style = 'bg:#81986D bold white'
format = '([\[$all_status$ahead_behind\]]($style))'


[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#E67E80 bold white"
format = '[🕑️ $time]($style)'

[status]
disabled = false
symbol = '✖'
success_symbol = '✔'
style = "bg:#E67E80 bold"
format = "[ $symbol]($style)"
