theme = "everforest_dark"

[editor]
color-modes = true
line-number = "relative"
cursorline  = true
bufferline  = "multiple"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "╎"

[editor.lsp]
display-messages = false
display-inlay-hints = true

