[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'shfmt', args = ["-i", "4"] }
auto-format = true


[[language]]
name = "nu"
indent = { tab-width = 4, unit = "    " }


[[language]]
name = "python"
language-servers = ["pyright"]


[[language]]
name = "rust"

[language-server.rust-analyzer.config.check]
command = "clippy"


[[language]]
name = "java"
indent = { tab-width = 4, unit = "    " }


[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }
auto-format = true


[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }
auto-format = true


[[language]]
name = "arduino"
scope = "source.arduino"
injection-regex = "arduino"
file-types = ["ino", "cpp", "h"]
comment-token = "//"
roots = ["sketch.yaml"]
language-servers = ["arduino-language-server"]
indent = { tab-width = 4, unit = "    " }
auto-format = true

[language.formatter]
command = "clang-format"

[language-server.arduino-language-server]
command = "arduino-language-server"

[[grammar]]
name = "arduino"
source = { git = "https://github.com/ObserverOfTime/tree-sitter-arduino", rev = "94219a5ac207a0fadd680b285378d08669d5bbc8" }


[[language]]
name = "latex"

[language.formatter]
command = "latexindent"
# auto-format = true

[language-server.texlab.config.texlab.build]
onSave = true
executable = "latexmk"
args = [
  "-lualatex",
  "-f",
  "-output-directory=build",
  "-interaction=nonstopmode",
  "--shell-escape",
  "-enable-write18",
  "--synctex=1",
  "%f"
]

[language-server.texlab.config.texlab.forwardSearch]
executable = "zathura"
args = ["--synctex-forward", "%l:1:%f", "%p"]

[language-server.texlab.config.texlab.chktex]
onEdit = true
onOpenAndSave = true

[language-server.texlab.config.texlab]
auxDirectory = "build"


[[language]]
name = "toml"

[language-server.taplo]
command = "taplo"
args = ["lsp", "stdio"]

[language.formatter]
command = "taplo"
args = ["fmt", "-c ~/.config/helix/.taplo.toml", "-"]
auto-format = true


[[language]]
name = "markdown"
auto-format = true

[language-server.mdpls]
command = "mdpls" # enable if editing wiki markdown files 
