[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'shfmt', args = ["-i", "4"] }
auto-format = true


[[language]]
name = "nu"
indent = { tab-width = 4, unit = "    " }


[[language]]
name = "python"
language-servers = ["pyright"]


[[language]]
name = "rust"

[language-server.rust-analyzer.config.check]
command = "clippy"


[[language]]
name = "java"
language-servers = ["jdtls"]
indent = { tab-width = 4, unit = "    " }

[language-server.jdtls.config.java.jdt.ls.java]
home = '/usr/lib/jvm/java-17-openjdk'


[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }
auto-format = true

[language.formatter]
command = "clang-format"


[[language]]
name = "arduino"
scope = "source.arduino"
injection-regex = "arduino"
file-types = ["ino", "cpp", "h"]
comment-token = "//"
roots = ["sketch.yaml"]
language-servers = ["arduino-language-server"]
indent = { tab-width = 4, unit = "    " }

[language.formatter]
command = "clang-format"

[language-server.arduino-language-server]
command = "arduino-language-server"
args = ["-fqbn", "arduino:avr:uno"]

[[grammar]]
name = "arduino"
source = { git = "https://github.com/ObserverOfTime/tree-sitter-arduino", rev = "db929fc6822b9b9e1211678d508f187894ce0345" }


[[language]]
name = "latex"
# auto-format = true

[language-server.texlab.config.texlab.build]
onSave = true
executable = "latexmk"
args = [
  "-lualatex",
  "-f",
  "-output-directory=build",
  "--synctex=1",
  "-interaction=nonstopmode",
  "%f",
]

[language-server.texlab.config.texlab.chktex]
onEdit = true
onOpenAndSave = true

[language-server.texlab.config.texlab]
auxDirectory = "build"


[[language]]
name = "toml"

[language-server.taplo]
command = "taplo"
args = ["lsp", "stdio"]

[language.formatter]
command = "taplo"
args = ["fmt", "-c ~/.config/helix/.taplo.toml", "-"]
auto-format = true


[[language]]
name = "markdown"
auto-format = true

[language-server.mdpls]
command = "mdpls" # enable if editing wiki markdown files 

# [language.formatter]
# command = "dprint"
# args = ["fmt", "--stdin", "md"]
